name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Looking for duplicates
        run: |
          sort README.md | uniq -d \
            | grep -v "###" | grep -v "div" \
            | grep -v "table-of-contents" | grep -v -e '^$'
